# Generated by Django 4.0 on 2022-11-30 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='categories',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=1981, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
