# Generated by Django 4.0 on 2022-11-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_categories_options_categories_created_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['-created_on'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
