# Generated by Django 4.0 on 2022-12-04 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_requirements_created_on_requirements_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='status',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='what_you_learn',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='what_you_learn',
            name='status',
        ),
        migrations.RemoveField(
            model_name='what_you_learn',
            name='updated_on',
        ),
    ]
