# Generated by Django 4.0 on 2022-12-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_lession_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='content',
        ),
    ]
