# Generated by Django 4.0 on 2022-12-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_course_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=100),
        ),
    ]
